### ISSUE TITLE
Redirect_uri error, can't login when forced to migrate to V3

### ISSUE THREAD

**Issue by lamblovebuttie** [WhyAsh5114/MyFit#167]
Today I was forced to login to V3, and when trying to login I get the redirect_uri error which prevents me from logging in via github. I've only ever logged in via github before.
Happens on both computer and mobile.

**Comment by WhyAsh5114** [comment]
Yeah, my bad, I was updating the domains and messed up for a bit. It should be fixed by now.

**Comment by lamblovebuttie** [comment]
Still getting the error:

"The redirect_uri is not associated with this application.

The application might be misconfigured or could be trying to redirect you to a website you weren't expecting."

Both V3 and the new V2 link you sent me in discussions have the error when trying to login.

**Comment by WhyAsh5114** [comment]
Ok, I didn't cross check it for GitHub, Google is working rn. I'll fix it soon

**Comment by WhyAsh5114** [comment]
Okay, both v2 and v3 auth is fixed with both Google and GitHub.
Try it now and lmk.

**Comment by WhyAsh5114** [comment]
@lamblovebuttie And also, in the discussion that you opened, please do let me know what all you didn't like in v3, so I can improve it in v4
